### ISSUE TITLE
Incorrect behavior with slash in address object

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#1]
When trying to add an address object with a "/" in the name, apply fails:

```
Error: Error applying plan:

1 error(s) occurred:

* fortios_firewall_object_address.test: 1 error(s) occurred:

* fortios_firewall_object_address.test: Error reading Firewall Object Address: status is error and error no is not found and http_status no is 400
```
Here's the main.tf:

```
resource "fortios_firewall_object_address" "test" {
  name = "test 10.0.0.0/24"
  type = "ipmask"
  subnet = "10.0.0.0/24"
}
```

After applying, the state seems to be broken. The object cannot be removed anymore.

**Comment by fwiethof** [comment]
The object is however, created on the firewall.
We assume there is an encoding issue with the URL.

**Comment by frankshen01** [comment]
Hi @fwiethof, thanks for reporting this issue. Sorry for the trouble here. This is caused by that the resource name in the GET URL is not encoded. We will fix it next.

**Comment by fwiethof** [comment]
I confirm it is working now with the fixed commit.

**Comment by frankshen01** [comment]
@fwiethof Glad it worked for you!
