### ISSUE TITLE
Allow to set order of security policies

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#10]
I believe it is currently not possible to manipulate the order of security policies using the provider.

Can you add before/after attributes taking the ID of another policy to make sure the new policy is before/after the referenced policy?

The FortiOS REST API is able to do it.

**Comment by frankshen01** [comment]
Hi @fwiethof, thanks for opening this issue :). The feature will be supported next.

**Comment by gaozb01** [comment]
Hi @fwiethof, ti-namemodify-import branch should have the feature you need now, please have a try if you want, thanks.

**Comment by fwiethof** [comment]
@gaozb01 i was on vacation. we will test this week.

**Comment by fwiethof** [comment]
@gaozb01 the code in the branch does not compile. can you double-check please?

**Comment by gaozb01** [comment]
Hi @fwiethof, there are some updates after my commit, the sdk part is submited to fgtdev/fortios-sdk-go, but not here, so leading to the errors you see. sorry about that, my mistake.

I have backported that part into this branch, and i double checked that it can build success on my side, please have a try again, thanks.

**Comment by fwiethof** [comment]
It compiles now. We try to test this week. I'll keep you updated.
Many thanks for you quick responses and dedication!

**Comment by ssinger1** [comment]
how is it possible to manipulate the order of security policies. i can not find anything in the documentation

**Comment by gaozb01** [comment]
Hi @ssinger1 , this feature is supported under branch ti-namemodify-import for now, for the related document, please refer to:
https://github.com/terraform-providers/terraform-provider-fortios/blob/ti-namemodify-import/website/docs/r/fortios_firewall_security_policyseq.html.markdown
Thanks.

**Comment by ssinger1** [comment]
I can confirm that manipulating the order of rules works fine.

**Comment by gaozb01** [comment]
Close the issue as the master branch already has this feature now.
