### ISSUE TITLE
Wrong prefix handling in firewall addresses

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#13]
Given the following Terraform code:

resource "fortios_firewall_object_address" "test" {
  name = "test_10.0.0.0_24"
  type = "ipmask"
  subnet = "10.0.0.0/24"
}

This applies fine.

However, when I apply again, it tries to change the address:

  ~ fortios_firewall_object_address.test
      subnet: "10.0.0.0 255.255.255.0" => "10.0.0.0/24"

When I use this code instead:

resource "fortios_firewall_object_address" "test" {
  name = "test_10.0.0.0_24"
  type = "ipmask"
  subnet = "10.0.0.0 255.255.255.0"
}

subsequent applys do not try to change the object.

So from my point of view, you need to convert prefix lengths to subnet masks before using the value in the REST API call.

**Comment by frankshen01** [comment]
This has been released in version 1.1.0 of the Terraform FortiOS provider.
