### ISSUE TITLE
No Proper Error Output

### ISSUE THREAD

**Issue by dbadola** [terraform-providers/terraform-provider-fortios#17]
Whenever there is a error on the firewall it gives out the output like below

`Error creating Firewall Security Policy: status is error and error no is -3 and http_status no is 500`

This doesn't really helps to understand where are we doing mistake. Can we have more elaborative error

**Comment by JonTheNiceGuy** [comment]
There is a general issue with FortiOS in that the API only returns the error code. If you have access to a Fortigate that you can run the script against, the following commands (I've found) are very helpful:

```
diagnose debug application httpsd -1
diagnose debug enable
```

This logs all the HTTP requests.

You may also find this helpful (it's what I use with the Ansible Modules)

```
diagnose debug cli 8
diagnose debug enable
```

This shows the commands that are executed on the FortiGate as the API Request is processed.

If your session expires while you're attempting to run these commands, then the statement `diagnose debug duration 480` extends the debugging session to 480 minutes (the maximum idle time you can be logged in for)

**Comment by gaozb01** [comment]
The fix has been pushed to master already.

Without the patch:
---------------
Error: Error updating Firewall Security Policy: status is error and error no is -651 and http_status no is 500

With the patch:
---------------
Error: Error updating Firewall Security Policy: status is error and error no is -651, details: Internal Server Error: Internal error when processing the request
