### ISSUE TITLE
Add option to provider configuration to check firewall certificate

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#2]
The provider accepts certificates from the firewall that it cannot verify.
This is a security issue, which is inacceptable for a security device like a firewall.
There should be an option to accept or reject invalid certificates.

**Comment by frankshen01** [comment]
Hi @fwiethof , do you mean the digital certificate in fortios_vpn_ipsec_phase1interface or the license in fortios_system_license_X?

**Comment by fwiethof** [comment]
@frankshen01 no, i mean the certificate of the fortigate used for management and api access.
the provider is using https to communicate with the fortigate.
It is about the certificate used there.
