### ISSUE TITLE
New object will be created

### ISSUE THREAD

**Issue by ssinger1** [terraform-providers/terraform-provider-fortios#20]
```
resource "fortios_firewall_object_address" "test" {
    name = "test 10.0.0.0/24"
    type = "ipmask"
    subnet = "10.0.0.0 255.255.255.0"
}
```

Creating a firewall object with the code above leads to a problem. 
When the object is created and a name is set it can't be changed later to a different value. 

_exp: name = "test 10.0.0.0/24" -> changing to: "second_test 10.0.0.0/24"_

The value will be updated, but changing back to "test 10.0.0.0/24" will create a new object.

**Comment by frankshen01** [comment]
Hi @ssinger1, thanks for reporting this issue. Sorry for the trouble here. The current provider does not support the modification of the name, and the description will be added to the document. We are considering adding modifications to the name later.

**Comment by fwiethof** [comment]
I regard this as a showstopper using the provider.
Please reconsider repriorisation.

**Comment by frankshen01** [comment]
Hi, @fwiethof , I agree with you, will try to add it, thanks!

**Comment by frankshen01** [comment]
This has been released in version 1.1.0 of the Terraform FortiOS provider.

**Comment by fwiethof** [comment]
Did you change the docs or did you change the code?

**Comment by sghaa** [comment]
Hi @fwiethof , added detection for modifying primary keys in the code,  the provider will disable the modification of the primary key and give a prompt. In fact, the providers I have seen so far have a parameter or a value returned as the primary key, and cannot be modified by default. If you have a better solution, please let me know, thanks!

**Comment by frankshen01** [comment]
Hi @fwiethof , added detection for modifying primary keys in the code,  the provider will disable the modification of the primary key and give a prompt. In fact, the providers I have seen so far have a parameter or a value returned as the primary key, and cannot be modified by default. If you have a better solution, please let me know, thanks!

**Comment by fwiethof** [comment]
This is working.
However this is not solving the problem.
Why don't you use the UID as the primary key?

**Comment by frankshen01** [comment]
Continued at #21
