### ISSUE TITLE
Error getting CA Bundle

### ISSUE THREAD

**Issue by dbadola** [terraform-providers/terraform-provider-fortios#22]
I just tested it v1.1.0 provider we might have to update the terraform website to include `insecure=true` variable or something because I am getting below error when i am just using this

```
provider "fortios" {
    hostname = "54.226.179.231"
    token = "jn3t3Nw7qckQzt955Htkfj5hwQ6jdb"
}

```

# error
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error occurred:
        * provider.fortios: Error getting CA Bundle, CA Bundle should be set when insecure is false
```

both `insecure` and `cabundlefile` are optional but i think one have to set

I solved it by using 
```
provider "fortios" {
    hostname = "54.226.179.231"
    token = "jn3t3Nw7qckQzt955Htkfj5hwQ6jdb"
    insecure = "true"
}

```

**Comment by frankshen01** [comment]
Very good suggestions, this will be added to the document in the next release.

**Comment by gaozb01** [comment]
Close the issue as the descritpions about 'insecure' and 'cabundlefile' are alredy added to the index.html for master branch.
