### ISSUE TITLE
Cannot create VIP

### ISSUE THREAD

**Issue by bjcone** [terraform-providers/terraform-provider-fortios#25]
Trying to create a VIP (fortios_firewall_object_vip) using both the examples and the values from the vip_test.go file. I have verified that my firewall access key is correct as I am able to create Global Settings (fortios_system_setting_global) and Security Policies (fortios_firewall_security_policy).

However, when attempting to create a VIP entry, I get the response 

> Error creating Firewall Object Vip: cannot get the right response
> on vip.tf line 1, in resource "fortios_firewall_object_vip" "v11":
> 1: resource "fortios_firewall_object_vip" "v11" {

My current VIP configuration looks like: 

> resource "fortios_firewall_object_vip" "v11" {
>     name = "rname"
>     extip = "1.1.5.0-1.1.6.0"
>     mappedip = ["22.2.2.2"]
>     comment = "Terraform Test"
>     extintf = "port3"
>     portforward = "enable"
>     protocol = "tcp"
>     extport = "2-3"
>     mappedport = "4-5"
> }

 and the fortios provider is:

> provider "fortios" {
>     hostname = "${var.fortigate_dev_ip}"
>     token = "${var.fortigate_api_key}"
>     insecure = true
> }

**Comment by frankshen01** [comment]
Hi, @bjcone  Thank you for reporting this. The fortis provider and fortiAPI do not support the automatic generation of mappedip now, if you change your configuration to:
```
resource "fortios_firewall_object_vip" "v11" {
	name = "rname"
	extip = "1.1.5.0-1.1.6.0"
	mappedip = ["22.2.2.2-22.2.3.2"]
	comment = "Terraform Test"
	extintf = "port3"
	portforward = "enable"
	protocol = "tcp"
	extport = "2-3"
	mappedport = "4-5"
}
```
it will be successfully executed.

**Comment by bjcone** [comment]
@frankshen01, thanks for the reply. It is certainly possible that I have something with my endpoint - I am running firmware version 6.0.4. However, using the configuration you suggested above I still get the same result:

> terraform apply --target="fortios_firewall_object_vip.v11"
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   + create
> 
> Terraform will perform the following actions:
> 
>    fortios_firewall_object_vip.v11 will be created
>   + resource "fortios_firewall_object_vip" "v11" {
>       + comment     = "Terraform Test"
>       + extintf     = "port3"
>       + extip       = "1.1.5.0-1.1.6.0"
>       + extport     = "2-3"
>       + id          = (known after apply)
>       + mappedip    = [
>           + "22.2.2.2-22.2.3.2",
>         ]
>       + mappedport  = "4-5"
>       + name        = "rname"
>       + portforward = "enable"
>       + protocol    = "tcp"
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> fortios_firewall_object_vip.v11: Creating...

And the result: 
 
> Error: Error creating Firewall Object Vip: cannot get the right response
> 
>   on vip.tf line 13, in resource "fortios_firewall_object_vip" "v11":
>   13: resource "fortios_firewall_object_vip" "v11" {

**Comment by frankshen01** [comment]
Hi, @bjcone, the terraform configuration should be correct, I have tried it on my side, the problem did not appear. It is more likely that there is a configuration conflict on the firewall. Can you try the following steps?

1. Configure the VIP through the WebUI, keep all vip configurations same with the above, and check if it can be configured. If it can be successfully configured, please see step 2; If it is unsuccessful, please locate whether there is a resource conflict, such as whether port3 is valid, whether the VIP name conflicts, etc.;

2. If 1 is successful, open the diagnose under the firewall CLI (as @JonTheNiceGuy  described in #17):
Diagnose debug enable
Diagnosis debug cli 8
Diagnose debug application httpsd -1
Then execute terraform apply, post the output information in the CLI  to here, we will help to analyze. (BTW: use "diagnostic debug disable"to turn off diagnose)

Thank you!

**Comment by bjcone** [comment]
Thanks for your pointers on this. I was able to get it working.
