### ISSUE TITLE
Add import for resources

### ISSUE THREAD

**Issue by fwiethof** [terraform-providers/terraform-provider-fortios#3]
While waiting for the provider, we have already configured our FortiGate firewalls with outputs and copy&paste templates.

We now want to move to the new provider, but it looks like the import schema is missing, so a `terraform import` is not possible.

We do not want to reconfigure the whole firewall.

Please add an import option.

**Comment by fwiethof** [comment]
@frankshen01 this is quite important for migrating to the provider.
any estimation when you can add it?

**Comment by frankshen01** [comment]
Hi, @fwiethof , we have received the request and we are analyzing it.

**Comment by frankshen01** [comment]
The import feature for all resources except the license resources has been supported in https://github.com/terraform-providers/terraform-provider-fortios/tree/ti-namemodify-import. Will make it into the next release.

**Comment by fwiethof** [comment]
hi @frankshen01 we will test and give feedback soon

**Comment by fwiethof** [comment]
I have successfully tested import with address objects.
We will now continue migrating our copy & paste configs to the provider.
This will allow us to import more resource types.
I keep you posted.

**Comment by gaozb01** [comment]
Close this issue as the master branch already has this feature now.
