### ISSUE TITLE
DNS over TLS Terraform argument 'fortios_system_setting_dns' resource 

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-fortios#33]
FortiOS seems to support 'DNS over TLS' as a Web GUI option (source: https://docs.fortinet.com/document/fortigate/6.2.0/new-features/642344/dns-over-tls ). Could be a good idea to add it to the resource arguments.

**Comment by frankshen01** [comment]
Hi @tkoeck  the feature will be implemented in the next release.

**Comment by gaozb01** [comment]
Already supported in master branch.
