### ISSUE TITLE
No static routing options in 'fortios_firewall_object_address' resource

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-fortios#36]
Hi,

the 'fortios_firewall_object_address' resource does not have a 'Static Route Configuration' argument. That unfortunately means that the routing has to be created in an extra step and has to be adjusted if the address will be changed.
The 'Show in Address List' argument isn't mapped, too.

Greetings
Tobias

**Comment by gaozb01** [comment]
Already supported in master branch.
