### ISSUE TITLE
Missing destination type "Internet Service" in fortios_networking_route_static

### ISSUE THREAD

**Issue by liquid-cloud** [terraform-providers/terraform-provider-fortios#39]
Hello,

According to https://www.terraform.io/docs/providers/fortios/r/fortios_networking_route_static.html it is not possible to create a Static Route referencing an Internet Service - which is possible using the UI as shown bellow:

![service](https://user-images.githubusercontent.com/49679701/64685107-ad513f80-d486-11e9-80a2-5d78320589e1.png)

Similar functionality seems to be available for `fortios_firewall_security_policy`

https://www.terraform.io/docs/providers/fortios/r/fortios_firewall_security_policy.html#internet_service_id

Would it be possible to add this functionality to the provider ?

Thank you !

**Comment by gaozb01** [comment]
Hi @liquid-cloud , this argument for "static route" resource will be supported in the next release version, our developer is working on it now. thanks.

**Comment by liquid-cloud** [comment]
Thank you for your fast response ! Is it possible to share when is next release?  (rough estimate is also fine)

**Comment by gaozb01** [comment]
We can not estimate the time yet, but probably somewhere in 2020.

**Comment by gaozb01** [comment]
Already supported in master branch.
