### ISSUE TITLE
fortios_firewall_security_policy - not possible to set order/priority

### ISSUE THREAD

**Issue by liquid-cloud** [terraform-providers/terraform-provider-fortios#43]
The "order" of the policies is important - as I understand the order is from TOP to BOTTOM and the last rule/policy should be "DENY anything".

Currently, we can drag and drop policies in the UI to order them, but it is not possible to set order/priority/id in the fortios_firewall_security_policy Terraform resource. As it is now, every new policy created with Terraform goes at the bottom of the list.

Is there a way to configure or implement this ordering in any way ?

Thank you!

**Comment by gaozb01** [comment]
Hi @liquid-cloud , you can have a try with fortios_firewall_security_policyseq resource, which should solve your problem. thanks.

**Comment by liquid-cloud** [comment]
Thank you, that solved it. The issue can be closed :)
