### ISSUE TITLE
Error updating System Setting Global: cannot get the right response

### ISSUE THREAD

**Issue by bkalai321** [terraform-providers/terraform-provider-fortios#46]
getting Error updating System Setting Global: cannot get the right response
provider "fortios" {
    hostname = "99.43.125.148"
    insecure = true
    token = "1hgktx7wh18scy7bjz7b44GfGhm3tx"
}
resource "fortios_system_setting_global" "bk-test" {
  hostname = "testForti"
  admin_sport = 443
  admin_ssh_port = 22
  timezone = "04"
}
terraform init and plan do't have any errors but when applying i get the above error.

Any help will be greatly appriciated

**Comment by gaozb01** [comment]
Hi @bkalai321 , i tried the config on my side and it works well. are you using the master branch? have you ever success with other fortios resource? thanks.

**Comment by bkalai321** [comment]
Thanks @gaozb01 for looking ionto this.
I tried to connect to another fortigate 60 and got the same error

**Comment by bkalai321** [comment]
this had to do with subnetting in our setup It's working now

**Comment by zx1986** [comment]
#37
