### ISSUE TITLE
Protocol FMG-Access in not working in under resource - fortios_networking_interface_port

### ISSUE THREAD

**Issue by bharat109puri** [terraform-providers/terraform-provider-fortios#49]
I created terraform resources fortios_networking_interface_port with following code :

resource "fortios_networking_interface_port" "wan1" {
    name = "wan1"
    ip = var.wan1_ip
    status = "up"
    device_identification = "disable"
    role = "wan"
    allowaccess = "ping https ssh http capwap FMG-Access"
    mode = "static"
    dns_server_override = "enable"
    defaultgw = "enable"
    type = "physical"
}

Its working fine but not adding FMG-Access protocol in fortiOS

**Comment by bharat109puri** [comment]
Screenshot of terraform plan:
always showing FMG-Access under plan but not doing anything while applying.

![image](https://user-images.githubusercontent.com/6189184/70245092-8790b980-179b-11ea-9611-44c5ab9034a3.png)

**Comment by frankshen01** [comment]
Hi @bharat109puri  please try to set with:

`allowaccess = "ping https ssh http capwap fgfm"`

This means: FMG-Access->fgfm. It should solve your problem. Reference: 
https://help.fortinet.com/cli/fos60hlp/60/Content/FortiOS/fortiOS-cli-ref/config/system/interface.htm

Thank you!

**Comment by bharat109puri** [comment]
Thanks @frankshen01
