### ISSUE TITLE
Resource fortios_firewall_object_address doesn't support import

### ISSUE THREAD

**Issue by crawfs** [terraform-providers/terraform-provider-fortios#54]
Hi,

I'm experimenting with the fortios provider in our environment and I'm running into a bit of a wall when trying to import resources, I'm able to successfully create new resources on the firewall but I can't seem to import existing ones and the provider exits with an error when it tries to create a resource that already exists.

```
terraform import 'module.fortios_subnet_addresses.fortios_firewall_object_address.subnet[\"azure-ea-corp-vnet\"]' "azure-ea-corp-vnet"
module.fortios_subnet_addresses.fortios_firewall_object_address.subnet["azure-ea-corp-vnet"]: Importing from ID "azure-ea-corp-vnet"...

Error: resource fortios_firewall_object_address doesn't support import
```

As per the above it appears that the provider does not support importing the fortios_firewall_object_address, is this expected behavior or am I doing something wrong?

**Comment by frankshen01** [comment]
hi @crawfs  The v1.1.0 release does not yet support import. But the master branch has support for import, can you try to compile it yourself by following the steps in the "Building the Provider" section of https://github.com/terraform-providers/terraform-provider-fortios?

**Comment by crawfs** [comment]
Hey thanks for the reply, I'm having some issues building the repo on windows 10 after following the instructions under the "building the provider" section:

```
C:\Go\src\github.com\terraform-providers\terraform-provider-fortios [master ≡]> $env:gopath
C:\go
C:\Go\src\github.com\terraform-providers\terraform-provider-fortios [master ≡]> go build
go: inconsistent vendoring in C:\Go\src\github.com\terraform-providers\terraform-provider-fortios:
        go.mod requires github.com/terraform-providers/terraform-provider-fortios  but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
C:\Go\src\github.com\terraform-providers\terraform-provider-fortios [master ≡]> go mod tidy; go mod vendor
C:\Go\src\github.com\terraform-providers\terraform-provider-fortios [master ≡ +0 ~346 -24 !]> go  build
go: inconsistent vendoring in C:\Go\src\github.com\terraform-providers\terraform-provider-fortios:
        go.mod requires github.com/terraform-providers/terraform-provider-fortios  but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
```

I also tried downloading make for windows to see if that made a difference compared to using "Go Build" but that provided the same error.

**Comment by crawfs** [comment]
I amanged to get the binary on windows by doing:

```
 go get github.com/terraform-providers/terraform-provider-fortios
```

**Comment by crawfs** [comment]
Ok that works by performing the following steps:

1. Install Go
2. ensure $PATH and $GOPATH variables are correctly configured
3. Run ```go get github.com/terraform-providers/terraform-provider-fortios``` this will install the binary for the repository @master into $GOPATH\bin
4. Place the terraform binary in $GOPATH\bin and make sure this is the binary being used in command line (This is the easiest way I found to make terraform pickup the exe)
5. Perform ```terraform init``` and ```terraform apply``` etc as usual, you should be using the imported fortios provider from step 3.

The only remaining is I have is from an outstanding issue with terraform: https://github.com/hashicorp/terraform/issues/13018 which means I can't perform the import without hardcoding the provider configuration which isn't an option because of the API token. Is there a workaround for this? 

I was able to successfully import from local by hardcoding the values but obviously I can't push this into our source code and have it running in a pipeline as is.

**Comment by frankshen01** [comment]
Hi @crawfs Please follow the steps below to set the token environment variable on your windows 10 to resolve your issue:

> Right Click On "This PC"->Properties->Advanced System Properties->Environment Variables->User variables for XXUSER->New...  :
>    Variable name:  FORTIOS_ACCESS_TOKEN
>    Variable value:   {{ your token value }}
> 
> Restart windows

Thanks!

**Comment by crawfs** [comment]
Thanks @frankshen01 that works as an option.
