### ISSUE TITLE
Terraform destroy doesn't deletes some sections

### ISSUE THREAD

**Issue by dbadola** [terraform-providers/terraform-provider-fortios#8]
Hi,

I tried to configured below sections first and tried to do  "taint" or "destroy" but not able to delete below sections. Terraform output says they get deleted and can't see them in the state file as well but the configurations still exists on the firewall

* Config system global
*  Interface IP
* DNS
* syslog
* ntp

**Comment by frankshen01** [comment]
Yes, you are right. They can only be updated by reconfiguration.

**Comment by dbadola** [comment]
@frankshen01  Thank you for the explanation
