### ISSUE TITLE
Dependency Functionality

### ISSUE THREAD

**Issue by dbadola** [terraform-providers/terraform-provider-fortios#9]
Depends on functionality are not working correctly. Creation of address group are failing due to address has not been created.  

Similarly Creation of firewall policy is failing because address group are not created.

Temporary workaround is to run the `terraform apply` again one more time

example output
```

Error: Error applying plan:

2 errors occurred:
        * module.config_firewall_address.fortios_firewall_object_address.address[0] (destroy): 1 error occurred:
        * fortios_firewall_object_address.address.0: Error deleting Firewall Object Address: status is error and error no is -23 and http_status no is 500


        * module.config_vpn.fortios_vpn_ipsec_phase1interface.phase1 (destroy): 1 error occurred:
        * fortios_vpn_ipsec_phase1interface.phase1: Error deleting VPN IPsec Phase1Interface: status is error and error no is -23 and http_status no is 500

```

**Comment by frankshen01** [comment]
hi, @dbadola I have tried the following configuration to the following configuration to verify the dependency function,  it's ok for me: 
resource "fortios_firewall_object_address" "t1" {
	name = "t1"
	type = "fqdn"
	fqdn = "google.com"
	comment = "Terraform Test"
}

resource "fortios_firewall_object_address" "t2" {
	name = "t2"
	type = "fqdn"
	fqdn = "microsoft.com"
	comment = "Terraform Test"
}

resource "fortios_firewall_object_addressgroup" "test3" {
	name = "t3"
	member = ["${fortios_firewall_object_address.t1.name}","${fortios_firewall_object_address.t2.name}"]
}

Can you please post your configuration? so we can analyze the problem. Thanks

**Comment by dbadola** [comment]
@frankshen01  Apologies I forgot to use them properly please ignore this one
